### ISSUE TITLE
Videos folder was empty

### ISSUE THREAD

**Issue by Yunahimesama21** [ReneR97/domestika-downloader#10]
Managed to solve the problem! The program was running great! It is my computer problem. Thank you So much ReneR97!

**Comment by Yunahimesama21** [comment]
also, i tried to download node js tool and run the project. This is the error i get.

TypeError: Cannot read properties of undefined (reading 'length')
    at getInitialProps (C:\Users\ShalMain\index.js:131:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async scrapeSite (C:\Users\ShalMain\index.js:56:25)

Thank you!
