### ISSUE TITLE
Can't get it to work with Plus courses

### ISSUE THREAD

**Issue by joelstitch** [ReneR97/domestika-downloader#21]
I have Domestika PLUS and would like to download some of the free courses but when I try one of the courses I get with PLUS I just get a Error message for all the video files.

**Comment by ReneR97** [comment]
Hello, 
can you send me the error message you get?

**Comment by joelstitch** [comment]
I actually got it confused with a similar github project but for this project I always get this error when I run the script even though I have Chronium installed.

```
/home/rw/domestika-downloader/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:289
                    throw new Error(`Could not find Chromium (rev. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/rw/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/home/rw/domestika-downloader/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:289:27)
    at ChromeLauncher.executablePath (/home/rw/domestika-downloader/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:182:25)
    at ChromeLauncher.computeLaunchArguments (/home/rw/domestika-downloader/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:99:37)
    at async ChromeLauncher.launch (/home/rw/domestika-downloader/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:83:28)
    at async scrapeSite (/home/rw/domestika-downloader/index.js:36:21)

Node.js v20.10.0
```

**Comment by fallenmaverick** [comment]
I am also not able to download domestika plus courses

**Comment by ReneReiterer** [comment]
Try running this command:

node node_modules/puppeteer/install.js

in the root folder, so the same folder you ran the above command.
That should install the needed chromium files. Sometimes puppeteer seems to not do that as its supposed to do.

**Comment by joelstitch** [comment]
```
I ran the command you gave me and it installed with no error but when I run **npm run start** I get this:

rw@rw:~/domestika-downloader$ npm run start

> domestika-downloader@1.0.0 start
> node index.js


  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.


  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

/home/rw/domestika-downloader/index.js:131
        for (let i = 0; i < data.videos.length; i++) {
                                        ^

TypeError: Cannot read properties of undefined (reading 'length')
    at getInitialProps (/home/rw/domestika-downloader/index.js:131:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async scrapeSite (/home/rw/domestika-downloader/index.js:56:25)

```

**Comment by kanishkamad** [comment]
![Viraj](https://github.com/ReneR97/domestika-downloader/assets/106143773/72333e50-a016-48c7-af77-bd287284e604)

Hi, I get this error. Can you tell me what did I do wrong ?

**Comment by princesadelaspampas** [comment]
> ![Viraj](https://private-user-images.githubusercontent.com/106143773/323402576-72333e50-a016-48c7-af77-bd287284e604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTIzNTcsIm5iZiI6MTcxNDQxMjA1NywicGF0aCI6Ii8xMDYxNDM3NzMvMzIzNDAyNTc2LTcyMzMzZTUwLWEwMTYtNDhjNy1hZjc3LWJkMjg3Mjg0ZTYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNzM0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDhjZGIwODUyNDdkYWY1NmViNTJlZWI4MTk2OTI4MDUyZGYyN2ViMzA3YjM0MDk5M2JlZmU4NzY3N2RmYjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vUF4yLq-cdNO-MLolGxlgSOJLnH5xxvNqUBb11wGquI)
> 
> Hi, I get this error. Can you tell me what did I do wrong ?

The 'credentials' cookie is not correct. If you can't find them on Chrome, try on Mozilla.

**Comment by MundoMedia** [comment]
The Cookie Editor plugin displays more info on the Firefox version than on the Chrome version.
Use Cookie Editor by cgagnier on Firefox for this.

**Comment by archz2** [comment]
> ![Viraj](https://private-user-images.githubusercontent.com/106143773/323402576-72333e50-a016-48c7-af77-bd287284e604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTUyODQsIm5iZiI6MTcyMDM1NDk4NCwicGF0aCI6Ii8xMDYxNDM3NzMvMzIzNDAyNTc2LTcyMzMzZTUwLWEwMTYtNDhjNy1hZjc3LWJkMjg3Mjg0ZTYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxMjIzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmVhNmEwYjRiOWJjOGJkMzM0NWU5N2Y2NDY1NjIyNDc2MjZiN2Q2Nzg0Njc1YzQ0MzhmOWI2YmFmNWFlNjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YO99UjIcEvOo_7YxMXFweboha85Yv_F1287qKliPRkY)
> 
> Hi, I get this error. Can you tell me what did I do wrong ?

I am also getting this error if use cookies from Firefox using the extension 'Cookie Editor by cgagnier' as suggested by @MundoMedia 

If I use cookies from Chrome, I get the error, 'Error Fetching Data, check the credentials are still valid.'.


This is specifically happening with courses that I have under 'plus' subscription. The courses that I have bought individually are getting downloaded fine using the chrome cookies. What should I do?

**Comment by MundoMedia** [comment]
Well done.
I was manually adding also, like you are, until I realized that if you go to the main course page for a Plus course, then click the 'Content' tab, it takes you to the /course page for that course.
Also note, the cookies and credentials will expire all during the day so you may find you have to regularly update them, and be careful not to accidentally replace more than the cookie or credential key in the script because that will also throw up a confusing error -- like it did with me when I did that. Although ChatGPT is your friend in these cases, I used it to add various functions to this script. Thanks again to the dev for an excellent solution.

**Comment by ArunaDurgaDevi** [comment]
@MundoMedia Can you please help me with downloading I don't know any js or node and I am unable to make it work. I am getting this error I literally don't know what I am doing

arunadurgadevirudrakshala@Arunas-Mac-mini domestika-downloader-main % /Users/arunadurgadevirudrakshala/Desktop/domestika-downloader-main/index.js npm run start
zsh: permission denied: /Users/arunadurgadevirudrakshala/Desktop/domestika-downloader-main/index.js
arunadurgadevirudrakshala@Arunas-Mac-mini domestika-downloader-main % /Users/arunadurgadevirudrakshala/Desktop/domestika-downloader-main/index.js npm i
zsh: permission denied: /Users/arunadurgadevirudrakshala/Desktop/domestika-downloader-main/index.js
arunadurgadevirudrakshala@Arunas-Mac-mini domestika-downloader-main %

**Comment by ArunaDurgaDevi** [comment]
@MundoMedia Please help 
<img width="2040" alt="Screenshot 2024-09-15 at 7 46 31 PM" src="https://github.com/user-attachments/assets/3e1421a0-c269-4076-8744-2732dbfa84e1">
<img width="1017" alt="Screenshot 2024-09-15 at 7 46 42 PM" src="https://github.com/user-attachments/assets/3d72198b-580b-4b04-ac2a-55f69087093a">
