### ISSUE TITLE
Unexpected token '&&='

### ISSUE THREAD

**Issue by hajimson** [ReneR97/domestika-downloader#49]
Hello there,

i've just encountered an error below:
I use Pop-OS linux.

```
/home/piotrek/Pobrane/domestika-downloader-main/node_modules/puppeteer-core/lib/cjs/puppeteer/util/disposable.js:9
Symbol.dispose ??= Symbol('dispose');
               ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/piotrek/Pobrane/domestika-downloader-main/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:13:25)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! domestika-downloader@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the domestika-downloader@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/piotrek/.npm/_logs/2024-07-17T13_06_02_981Z-debug.log

````

**Comment by ReneR97** [comment]
Linux isnt officially supported so its hard for me to give you good help, sorry
