### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by Marco96c** [ReneR97/domestika-downloader#51]
I'm facing this error. What's tje problem?
```
npm run start

> domestika-downloader@1.0.0 start
> node index.js

node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at new Process (D:\Marco\domestika-downloader-main\node_modules\@puppeteer\browsers\lib\cjs\launch.js:146:56)
    at launch (D:\Marco\domestika-downloader-main\node_modules\@puppeteer\browsers\lib\cjs\launch.js:50:12)
    at ChromeLauncher.launch (D:\Marco\domestika-downloader-main\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:87:54)
    at async scrapeSite (D:\Marco\domestika-downloader-main\index.js:40:21) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Node.js v20.16.0
```

**Comment by ReneR97** [comment]
Are you on Mac or Windows?
