### ISSUE TITLE
decodeURI fix

### ISSUE THREAD

**Issue by ignas-x** [ReneR97/domestika-downloader#61]
Hi, program is throwing an error on index.js line 37

```
c:\Users\.........\Domestika\domestika-downloader-main\index.js:37
const access_token = regex_token.exec(decodeURI(_credentials_))[1];
                                                               ^
TypeError: Cannot read properties of null (reading '1')
    at Object.<anonymous> (c:\Users\ig\Downloads\_Domestika\domestika-downloader-main\index.js:37:64)
```

This happens because **decodeURI** isn't enough to decode _\_credentials\__ cookie (there are still leftovers like %3A %2C), so I replaced it with  **decodeURIComponent** and it works like a charm now. Thanks a lot for this tool!

![image](https://github.com/user-attachments/assets/2929b61e-807f-44db-91da-8e15c8c4ed4d)

**Comment by ReneR97** [comment]
you can make a pull request if you want, Will be happy to merge it

**Comment by fjordkn** [comment]
i tried adding this to the code too, but i still get the same error

**Comment by Mark-Kent** [comment]
Any help. getting the same error

**Comment by Mark-Kent** [comment]
const access_token = regex_token.exec(decodeURI(_credentials_))[1];
                                                               ^

TypeError: Cannot read properties of null (reading '1')
    at Object.<anonymous> (D:\Downloads\domestika-downloader-main\index.js:39:64)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49

**Comment by kitzstanza** [comment]
I was getting the same things (Mac silicon). I dug a little and did some copilot and it seems to have been a this:
const access_token = regex_token.exec(decodeURI(_credentials_))[1];

the decodeURI() left the access token with an opening quote, so Invalid JSON and Unmatchable by the regex: /accessToken\":\"(.*?)\"/gm, which made const access_token = regex_token.exec(decodeURI(_credentials_))[1]; return null

i got it working by re-encoded the JSON using encodeURI('{"accessToken":"MY TOKEN","isEmpty":false}')

I also had to dequaratine the N_m3u8DL-RE script, but then it worked.

**Comment by Mark-Kent** [comment]
> I was getting the same things (Mac silicon). I dug a little and did some copilot and it seems to have been a this: const access_token = regex_token.exec(decodeURI(_credentials_))[1];
> 
> the decodeURI() left the access token with an opening quote, so Invalid JSON and Unmatchable by the regex: /accessToken":"(.*?)"/gm, which made const access_token = regex_token.exec(decodeURI(_credentials_))[1]; return null
> 
> i got it working by re-encoded the JSON using encodeURI('{"accessToken":"MY TOKEN","isEmpty":false}')
> 
> I also had to dequaratine the N_m3u8DL-RE script, but then it worked.

**I got it work by reinstalling N_m3u8DL-RE. Thanks for your input though.**
